version: '3.5'

services:
  fiaptrip-db:
    image: postgres:latest
    container_name: fiaptrip-db
    environment:
      POSTGRES_DB: "fiaptrip"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - fiaptrip:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  fiaptrip:
