version: '3.5'

services:
  fiaptrip-db:
    image: postgres:latest
    container_name: fiaptrip-db
    environment:
      POSTGRES_DB: "fiaptrip"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - fiaptrip:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fiaptrip
    restart: unless-stopped

  fiaptrip-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fiaptrip-app:latest
    container_name: fiaptrip-app
    ports:
      - "3000:3000"
    networks:
      - fiaptrip
    depends_on:
      - fiaptrip-db

networks:
  fiaptrip:

volumes:
  fiaptrip:
